name: CI
on:
  push:
    branches:
      - staging
      - trying

jobs:

  test_linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.26.0, 1.31.0, stable, beta, nightly]
    steps:
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        run: ./ci/test_full.sh

  test_macOS:
    name: Test on macOS 11
    runs-on: ubuntu-latest
    steps:
      - name: System install
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: i586-unknown-linux-gnu
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target i586-unknown-linux-gnu --all-features


  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0
          profile: minimal
          override: true
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
