# Test pre-releases on a larger scope (platforms & versions) to avoid bad surprises.

name: Large scope
on:
  push:
    branches:
      - staging

permissions: {}

jobs:
  test-versions:
    name: Tests on Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        rust: [1.78.0, beta, nightly]

    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache crates from crates.io
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-hash-${{ hashFiles('Cargo.toml') }}

      - name: Quality - cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Quality - cargo clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build (dev)
        run: cargo build --all-features

      - name: Build (release)
        run: cargo build --all-features --release

      - name: Install cargo-nextest
        uses: taiki-e/install-action@58e862542551f667fa44c8a2a4a1d64ad477c96a # v2.75.17
        with:
          tool: cargo-nextest@0.9.133

      - name: Test
        run: ./ci/test_full.sh

  test-other-platforms:
    name: Tests on
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            target: x86_64-apple-darwin
            type: unix
            toolchain: stable
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            type: unix
            toolchain: stable
          - os: macos-latest
            target: aarch64-apple-darwin
            type: unix
            toolchain: stable
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            type: windows
            toolchain: stable
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache crates from crates.io
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('Cargo.toml') }}

      - name: Build (dev)
        run: cargo build --all-features

      - name: Build (release)
        run: cargo build --all-features --release

      - name: Install cargo-nextest
        uses: taiki-e/install-action@58e862542551f667fa44c8a2a4a1d64ad477c96a # v2.75.17
        with:
          tool: cargo-nextest@0.9.133

      - name: Test
        run: ./ci/test_full.sh
