name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # 00:00 Sunday

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.50.0, stable]
    steps:
      - name: Rust install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        run: ./ci/test_full.sh
